/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package modul3;

import modul3.models.DataPassword;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
       try {
            DataPassword.loadCSVData();
            Mainpage mainPage = new Mainpage(80);
            mainPage.draw();

            DataPassword.saveCSVData();
            // PasswordStore pass1 = new PasswordStore("AkunBerbahaya", "123423", "RahasiaDapur");
            // pass1.setCategory(PasswordStore.CAT_MOBILEAPP);
            // System.out.println(pass1);
            // System.out.println("USERNAME: " + pass1.username + " PASSWORD: " + pass1.getPassword());
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}
